image:
  name: registry.gitlab.com/enbuild-staging/hardened-gitlab-runner:v2

workflow:
  rules:
    # Always create a pipeline
    - when: always

stages:
  - deploy
  - destroy

deploy-bigbang:
  stage: deploy
  script: ./deploy.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE =~ /.*run-ci.*/i

destroy-bigbang:
  stage: destroy
  script: ./destroy.sh
  rules:
    - when: manual
      allow_failure: false
