apiVersion: v1
data:
  values.yaml: IyAtLSBUb2dnbGUgZGVwbG95bWVudCBvZiBFQ0sgT3BlcmF0b3IuCmVuYWJsZWQ6IHRydWUKZ2l0OgogIHJlcG86ICJodHRwczovL2dpdGxhYi5jb20vZW5idWlsZC1zdGFnaW5nL2NoYXJ0cy9lY2stb3BlcmF0b3IuZ2l0IgogIHBhdGg6ICIuL2NoYXJ0IgogIHRhZzogIjIuMy4wLWJiLjAiCiMgLS0gRmx1eCByZWNvbmNpbGlhdGlvbiBvdmVycmlkZXMgc3BlY2lmaWNhbGx5IGZvciB0aGUgRUNLIE9wZXJhdG9yIFBhY2thZ2UKZmx1eDoge30KIyAtLSBWYWx1ZXMgdG8gcGFzc3Rocm91Z2ggdG8gdGhlIGVjay1vcGVyYXRvciBjaGFydDogaHR0cHM6Ly9naXRsYWIuY29tL2VuYnVpbGQtc3RhZ2luZy9jaGFydHMvZWNrLW9wZXJhdG9yLmdpdAp2YWx1ZXM6CiAgaW1hZ2U6CiAgICByZXBvc2l0b3J5OiByZWdpc3RyeS5naXRsYWIuY29tL2VuYnVpbGQtc3RhZ2luZy9jb250YWluZXJfcmVnaXN0cnkvZWxhc3RpYy1lY2stb3BlcmF0b3IvZWNrLW9wZXJhdG9yCiAgdXBncmFkZUNyZHM6CiAgICBpbWFnZToKICAgICAgcmVwb3NpdG9yeTogcmVnaXN0cnkuZ2l0bGFiLmNvbS9lbmJ1aWxkLXN0YWdpbmcvY29udGFpbmVyX3JlZ2lzdHJ5L2JpZy1iYW5nLWJhc2UK
kind: Secret
metadata:
  creationTimestamp: null
  name: eckoperator-values
