---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bigbang
resources:
  - clusterauditor.enc.yaml
  - eckoperator.enc.yaml
  - fluentbit.enc.yaml
  - gatekeeper.enc.yaml
  - istiooperator.enc.yaml
  - istio.enc.yaml
  - monitoring.enc.yaml
  - private-registry.enc.yaml
  - repo.enc.yaml
  - repository-credentials.enc.yaml
  - twistlock.enc.yaml
