apiVersion: v1
kind: Secret
metadata:
    name: private-registry
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeTEuZHNvLm1pbCI6eyJ1c2VybmFtZSI6Ikp1bmVkX01lbW9uIiwicGFzc3dvcmQiOiJKWkhGWGQwdUdiRzR4WUdZZVNWV3FpbXVmWEhNd1giLCJhdXRoIjoiU25WdVpXUmZUV1Z0YjI0NlNscElSbGhrTUhWSFlrYzBlRmxIV1dWVFZsZHhhVzExWmxoSVRYZFkifX19
