apiVersion: v1
kind: Secret
metadata:
    name: private-registry
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:R/DACN/tdCg4r4md2g7qP7x3AOiAay53ZFpZ0rD6iYpaTFEFdxcN+bhZ3o5aF66gNQqdTVg/nE/BzsWfxYQUchFHtIHtZo6ODVwvM1yz/sANT17j08/pbFp4BZorhvIBnLvSY3bdLMQK/cOI5wJNhx3FNvt2cvr+1PKnVdFnplXIVQABNaCHjUkIhz0P7mbUWkD/UlofSGIxEzRbZvn1mw5NYrUdbeiDTntwaUViiObKXNlzYK2elKFVy7NcBzJkK8EfDX3CvLmbXiyAcvdlF+WqtD5wjrlTyKh8HOjYwXc=,iv:gJkbpDX4yiddH2iq6xIyPgmLh+KuZtIA3c/7OXcVOac=,tag:3Hl+bQjbaLfsviklhYxk9A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/d8e2b52a-4be9-4cbf-a59d-3ed92edf478b
          created_at: "2026-03-12T11:34:31Z"
          enc: AQICAHjl5FYZ43dNp8mgKeMSP43lKmqG9yGexqjczXkd0u5ShwGtWgSOMRT0xI8JwOr32HLRAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOom2tEZAcUJov+PsAgEQgDtmPgkN1tr27DpuW90E/x1lgtGo1KF+VNaTrk9KwGXIEXZYbIwH+0La5ADaeMk5hPvKzHxaZ7Afp0qiLw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-12T11:34:32Z"
    mac: ENC[AES256_GCM,data:Evm3Pejl2kz2Z0GZyAdqjTDIaAKBCnsVBW/C9i7pVVb4lISBgIMQviha0SQWHm4hpbqLpfMtTBqcAlDmCu0qE4WWVZ7CeR7Z3RE8BUFr2QY/8fJywg3j6pvWIqMyTE9KWHur60G1sksAKfj/C+zsx8WdyNYcSol+4BiVWhYu88U=,iv:oWlCb+u9D/XmCI0tsMHYVCitGvxPUPP26OHLalf1NgM=,tag:1XaTiZdgh2MOqdFrI4nt2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
