apiVersion: v1
kind: Secret
metadata:
    name: repository-credentials
    namespace: bigbang
type: Opaque
data:
    password: ENC[AES256_GCM,data:mRFBhCFh941EYV6QyPjlesNv6jPbYgegZkfQzQ==,iv:3vABnhgUjIjQ1z8oLQGV7Uy4269RZfiLx1sQ0mwOQqI=,tag:3N3J/5g1ISjrk/Fr6VG1MQ==,type:str]
    username: ENC[AES256_GCM,data:DkuH7gMkv5U32ePVOMSvZV8r/d+dQjBp+RLTDytl4jijwi0m,iv:Ezc0o36SlR4ms+FuYQ5dVcdHznAPPdzy1DreWaEZlPQ=,tag:7mZk6j1n/fSuXvVmJYB8Vw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/d8e2b52a-4be9-4cbf-a59d-3ed92edf478b
          created_at: "2026-03-12T12:49:13Z"
          enc: AQICAHjl5FYZ43dNp8mgKeMSP43lKmqG9yGexqjczXkd0u5ShwG1T/F5YCEcLRHHLjsZRZpnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNYFyMFTPxkiXvilOAgEQgDvlXpFKLuUIUOouqXz76onArg5W6N2Ih+ILhfGqQ7yTTm23aE03dAxUl3BaDtEAPN7f+TAZ7f5ECt4cZQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-12T12:49:14Z"
    mac: ENC[AES256_GCM,data:H9zo61GTNWCyZYudDO465tWc5KO02JwtEEhQseqNdCa3JkxOV12nVyajPv0oHntrM+DGbBi/vHZZ8j5ZMjREfy6lV0tgq6BDN+zxPkwC+msiJysSaj+JrxQKc8BgwrfLLtwKXK3uGfM5xCZXkJSa0V5MDV5Lch4Zg2WQaexyAZI=,iv:VkydRi73yH4UOZzJoUK0LGDSiL9IahLvWm/6YJzIt3A=,tag:RaIFiQqU7ZBtB8aP2hRfPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
