apiVersion: v1
kind: Secret
metadata:
    name: repo-values
spec: {}
data:
    values.yaml: ENC[AES256_GCM,data:WoNwU1mY45nSZ32Y6tFLR3RIPazNH+CLlMjpPYx/UboWirzgnm6QBqjb77C9Dl5zn6vDxfwvR0lKAO233k+0oamdW45ikNmP/ZpRirPuCnLEBy4kinc2CERl6KB+8qHYNfJwnwOuBzEC8YOl+Rzv1q0KKRGxEsZQWGjQCdo0OJ1YQdBpBwTcYAlMCOSjRTH3WVRVeAlkXkXTnKjyf5uqMQ==,iv:KGhFs6kUJbrMXW4+3EazgxXSlF6/fJYaXO+S1qbaxdc=,tag:7nFSVtXP8EKFgT9ezC3tcA==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/d8e2b52a-4be9-4cbf-a59d-3ed92edf478b
          created_at: "2026-03-12T12:38:29Z"
          enc: AQICAHjl5FYZ43dNp8mgKeMSP43lKmqG9yGexqjczXkd0u5ShwErcjiPv3rk9s8mNWPsbHpjAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6vKrtcGizOQbVShNAgEQgDsf6OEaKA9Lw9m1hgG8YyCidDr04b81FDFHAAddCa8Kstl/+2VNC/6UA2TJ/CRhX1vPdkPVBZl576vLBw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-12T12:38:31Z"
    mac: ENC[AES256_GCM,data:VXPFnfVWM3f9pY9zBUr5aTabV+072LyPbVxSRGW6kEiTqEtfmOuuMMzIJ/zgFT8J0A+VRR9tKjx0xAaZylUnjy9KPbchI0vuWu3+hlxY/XdXu5U3CvUgtZG/riEEcaVsBEwIGgpAXXuZdPzv/IjR1R88rpV7kECy66HBaGDhSVg=,iv:NfPH/YCOvZ/s1VpNG9bpK9oUIY/rmN9MufJEnlZ/Jz0=,tag:RVlmUCoryDIvhJlchwM0sw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
