apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:RJ2qsc8O2KPJBl+G8sQZP56eYaWghGeDg/JrgB2fcZUyrXJRanQcZbvLjRPSYTwFToZorpttSs6X67aUTQd+NeauhRssBJ48+VDPqDKw+sm0PBHbGJ45ViVlj0btnUpH5nYHUKBbZ3DKvAGI2dgY8w==,iv:JRw9fiw5kdz4hFWQBOeWYHuEnZDulKeiz7qfu44uOIU=,tag:YaVhM74FSjULn/M1hTYfCg==,type:str]
kind: Secret
metadata:
    name: repo-values
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/d8e2b52a-4be9-4cbf-a59d-3ed92edf478b
          created_at: "2026-03-12T12:34:47Z"
          enc: AQICAHjl5FYZ43dNp8mgKeMSP43lKmqG9yGexqjczXkd0u5ShwHHi5lkNUjcYfjPvB2l6EJgAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMaNM2Q7Jswyq9BpJxAgEQgDvgqISDNQJjMRzzvYW1UHLUHK54LGdLd5VhEgYx+O6YgS818YxDuW0iRs//8g/wQ2lm67CZkcD5HkL/pw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-12T12:34:48Z"
    mac: ENC[AES256_GCM,data:De7A5DgYPvZsthqbK3DW327rdvaZwf/sKS81JhhidZOXVzp79sAAQMw4nyuBPpgEPU/QDwfyYBpzjnC0dBOQGPqfSc7Wpvlu59vXmC6k4NM7TGw0Lo590nex4iDTnAVtGqbKc7BOYQLAIckAEIqP+TQ9RIAUpKwyiKLEPr88/L8=,iv:tAcZfy1syZFm718PjyniYZlntCHDG1nViXSN1J6mqh4=,tag:/xB/88JMHJtBtHKwKQRaYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
