apiVersion: v1
data:
    password: ENC[AES256_GCM,data:2PRfMk93Xj4n8jL3YNU8ikjvJiSh9+WtM9spYCC+njL0QJNZ0RhpVg3p8baHIletgQPXijFemxk=,iv:MxUzFRFdsj9HwCKTv2hQWjmGaNERz3uLYEJygBTnc/o=,tag:KMD6SDWZZUL9JkBP+AjmLQ==,type:str]
    username: ENC[AES256_GCM,data:BgPXT9rKNKs+dP5P7e79FQ==,iv:YqKu3Y9I3yI8jILFZQQ/OLNPYWXrbKQBJXDO9rxPEIk=,tag:i8unsLRxvCWMCfaRwDzvDA==,type:str]
kind: Secret
metadata:
    name: repository-credentials
    namespace: bigbang
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/cf300a49-6d7b-4faa-b63b-e8a48b15e97c
          created_at: "2023-12-22T13:10:40Z"
          enc: AQICAHgEZc9juNOu8iTsr3rG50GEd18jPYvnkcOlGDPahEQSpgFjNe/y6ZGPgBlTYohMLkfYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUjZ1dNqKDfqeUgjjAgEQgDsbLjsHHNAAs+p1biUD6yXc3GLoMBzyQlQsgVOrfs7oVLJJd9KdscVD5hUKu6fw8fJBU/O8iyF/6uqo2A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T13:10:41Z"
    mac: ENC[AES256_GCM,data:CgPEc9kz5FD5qFYBL60v7hBCGKI9pB5ABR1W2uWu/KS3pm+NMx523HE5mRy8Rb7Ar1vcR3UsT5kJ9Lb+hyHo/S8Cf98f5Yq3v/oWhQR0wuQgRgqrYMHA4E6bME1Lpczpa/OEHG1p+Rl4hMiOZ8x+0c9Tgp+UUriPW+9WP9Yo4No=,iv:EOxmMC73ta6OoNc0Ql8U4itLZOk847gtge0lnOKNBU4=,tag:MWxH0i9L4YXjjPgT9xpEfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
