apiVersion: v1
kind: Secret
metadata:
    name: repo-values
spec: {}
data:
    values.yaml: ENC[AES256_GCM,data:rwICoRgIQhuexGb8xJcbM0C+Nw77don6+XWoQ3grws1PV62tw5j9CgdKnXzKb9yS38Yo6BhpcJdO8PsoXF6fBi3rwlzK5IcpRuHal510oqArp3j2BKM0ocWTqWK3CgIm7QQ7ozanwqpi4sTahiRcQCcVtEkMHZQDYp6TWCFX15pZoOM664AJm68An5QtbxR/DgR5iBQ6yUK5Fg7BBAgt8w==,iv:DtMmG+usU4Q6Ciq/iE+i1FbfERyAP582+OXh0Z8E/G4=,tag:H+XAMnudRm72DIP/TAfK5A==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:986602297069:key/d8e2b52a-4be9-4cbf-a59d-3ed92edf478b
          created_at: "2026-03-12T12:52:50Z"
          enc: AQICAHjl5FYZ43dNp8mgKeMSP43lKmqG9yGexqjczXkd0u5ShwErtwIEGWHwPD5MjW96bXDrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMc35DhMBELoABGkRFAgEQgDvTRsFYVbvhH17Aiiky7A+kFmi9N5kS0pEuNRBbccqm5HTZgJ4pKtmr8iewdoPCwDQpfSu4luobqiCthg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-12T12:52:51Z"
    mac: ENC[AES256_GCM,data:RtqDHLmD+NUt+kWEt6TNrBATuj3scvBVFe5FXjH6uVGgztzsn8Tu/9OULgXHcX7lUml9lEogXUn//1CiYNgl3A70LrmUXmBN+QHBgEgfyQ88ZPEAa7PdZ8BVwmDoBKikdpnOxg2l2H77MYNoIneRbF3fJR2iYvlQ1SVhrcheLhE=,iv:MB540b1CLGEb/jXwQqb0evDyngnW7+E7G55RT/Rg7aA=,tag:AklnQ/rOjMtBj+Wx2SsqlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
