apiVersion: v1
kind: Secret
metadata:
    name: repository-credentials
    namespace: bigbang
type: Opaque
data:
    password: YVNYQUdmeXpMWGlNM0FGaFlzSFQ=
    username: Z2l0bGFiK2RlcGxveS10b2tlbi01MjA4OTM=
