kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: global-unrestricted-psp
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"policy/v1beta1","kind":"PodSecrityPolicy","metadata":{"annotations":{"seccomp.security.alpha.kubernetes.io/allowedProfileNames":"*"},"creationTimestamp":"2021-02-01T00:12:52Z","managedFields":[{"apiVersion":"policy/v1beta1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:allowPrivilegeEscalation":{},"f:allowedCapabilities":{},"f:fsGroup":{"f:rule":{}},"f:hostIPC":{},"f:hostNetwork":{},"f:hostPID":{},"f:hostPorts":{},"f:privileged":{},"f:runAsUser":{"f:rule":{}},"f:seLinux":{"f:rule":{}},"f:supplementalGroups":{"f:rule":{}},"f:volumes":{}}},"manager":"rke2","operation":"Update","time":"2021-02-01T00:12:52Z"}],"name":"global-unrestricted-psp","selfLink":"/apis/policy/v1beta1/podsecuritypolicies/global-unrestricted-psp","uid":"b33c11bb-4797-4dfd-813f-a65c1c6df6f8"},"spec":{"allowPrivilegeEscalation":true,"allowedCapabilities":["*"],"fsGroup":{"rule":"RunAsAny"},"hostIPC":true,"hostNetwork":true,"hostPID":true,"hostPorts":[{"max":65535,"min":0}],"privileged":true,"runAsUser":{"rule":"RunAsAny"},"seLinux":{"rule":"RunAsAny"},"supplementalGroups":{"rule":"RunAsAny"},"volumes":["*"]}}
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowedCapabilities:
    - '*'
  volumes:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostPID: true
  hostIPC: true
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  allowPrivilegeEscalation: true