---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bigbang
spec:
  interval: 1m0s
  url: https://github.com/VivSoftOrg/bigbang.git
  ref:
    tag: 1.42.0
  secretRef:
    name: repository-credentials