---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: bigbang
  interval: 2m0s