apiVersion: v1
data:
  istiooperator.yaml: |
    # -- Toggle deployment of Istio Operator.
    enabled: true
    git:
      repo: "https://gitlab.com/enbuild-staging/charts/istio-operator.git"
      path: "./chart"
      tag: "1.14.3-bb.0"
    # -- Flux reconciliation overrides specifically for the Istio Operator Package
    flux: {}
    # -- Values to passthrough to the istio-operator chart: https://gitlab.com/enbuild-staging/charts/istio-operator.git
    values:
      hub: registry.gitlab.com/enbuild-staging/container_registry/opensource-istio
      tidHub: registry.gitlab.com/enbuild-staging/container_registry/tetrate-istio
    # -- Post Renderers.  See docs/postrenders.md
    postRenderers: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: istiooperator-values
