apiVersion: v1
data:
  kiali.yaml: |
    # -- Toggle deployment of Kiali.
    enabled: true
    git:
      repo: "https://gitlab.com/enbuild-staging/charts/kiali.git"
      path: "./chart"
      tag: "1.55.0-bb.0"
    # -- Flux reconciliation overrides specifically for the Kiali Package
    flux: {}
    # -- Redirect the package ingress to a specific Istio Gateway (listed in `istio.gateways`).  The default is "public".
    ingress:
      gateway: ""
    sso:
      # -- Toggle SSO for Kiali on and off
      enabled: false
      # -- OIDC Client ID to use for Kiali
      client_id: ""
      # -- OIDC Client Secret to use for Kiali
      client_secret: ""
    # -- Values to pass through to Kiali chart: https://gitlab.com/enbuild-staging/charts/kiali
    values:
      image:
        repo: registry.gitlab.com/enbuild-staging/container_registry/opensource-kiali/kiali-operator
      cr:
        spec:
          deployment:
            image_name: registry.gitlab.com/enbuild-staging/container_registry/opensource-kiali/kiali
      svcPatchJob:
        image:
          repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang-base
    # -- Post Renderers.  See docs/postrenders.md
    postRenderers: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kiali-values
