---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bigbang
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: bigbang
configMapGenerator:
- name: bb-helm-values
  files:
    - alloy.yaml
    - anchoreenterprise.yaml
    - argocd.yaml
    - authservice.yaml
    - backstage.yaml
    - bbctl.yaml
    - disableautomaticpassthroughvalues.yaml
    - eckoperator.yaml
    - elasticsearchkibana.yaml
    - externalsecrets.yaml
    - fluentbit.yaml
    - fortify.yaml
    - gatekeeper.yaml
    - gitlab.yaml
    - gitlabrunner.yaml
    - grafana.yaml
    - haproxy.yaml
    - harbor.yaml
    - headlamp.yaml
    - istiocrds.yaml
    - istiogateway.yaml
    - istiod.yaml
    - keycloak.yaml
    - kiali.yaml
    - kyverno.yaml
    - kyvernopolicies.yaml
    - kyvernoreporter.yaml
    - loki.yaml
    - mattermost.yaml
    - mattermostoperator.yaml
    - metricsserver.yaml
    - mimir.yaml
    - minio.yaml
    - miniooperator.yaml
    - monitoring.yaml
    - neuvector.yaml
    - nexusrepositorymanager.yaml
    - packages.yaml
    - prometheusoperatorcrds.yaml
    - repo.yaml
    - sonarqube.yaml
    - tempo.yaml
    - thanos.yaml
    - twistlock.yaml
    - vault.yaml
    - velero.yaml
    - wrapper.yaml
