apiVersion: v1
data:
  kyverno.yaml: |
    # -- Toggle deployment of Kyverno.
    enabled: false
    git:
      repo: "https://gitlab.com/enbuild-staging/charts/kyverno.git"
      path: "./chart"
      tag: "2.5.3-bb.0"
    # -- Flux reconciliation overrides specifically for the Kyverno Package
    flux: {}
    # -- Values to passthrough to the kyverno chart: https://gitlab.com/enbuild-staging/charts/kyverno.git
    values:
      image:
        repository: registry.gitlab.com/enbuild-staging/container_registry/nirmata-kyverno
      initImage:
        repository: registry.gitlab.com/enbuild-staging/container_registry/nirmata-kyvernopre
      testImage:
        repository: registry.gitlab.com/enbuild-staging/container_registry/redhat-ubi/ubi8-minimal
      webhooksCleanup:
        image: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes/kubectl:v1.24.4
      bbtests:
        scripts:
          image: registry.gitlab.com/enbuild-staging/container_registry/opensource-kubernetes/kubectl:v1.24.4
    # -- Post Renderers.  See docs/postrenders.md
    postRenderers: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: kyverno-values
