logging:
  # -- Toggle deployment of Logging (EFK).
  enabled: false
  git:
    repo: "https://github.com/VivSoftOrg/elasticsearch-kibana.git"
    path: "./chart"
    tag: "0.14.0-bb.0"
  # -- Flux reconciliation overrides specifically for the Logging (EFK) Package
  flux:
    timeout: 20m
  # -- Redirect the package ingress to a specific Istio Gateway (listed in `istio.gateways`).  The default is "public".
  ingress:
    gateway: ""
  sso:
    # -- Toggle OIDC SSO for Kibana/Elasticsearch on and off.
    # Enabling this option will auto-create any required secrets.
    enabled: false
    # -- Elasticsearch/Kibana OIDC client ID
    client_id: ""
    # -- Elasticsearch/Kibana OIDC client secret
    client_secret: ""
  license:
    # -- Toggle trial license installation of elasticsearch.  Note that enterprise (non trial) is required for SSO to work.
    trial: false
    # -- Elasticsearch license in json format seen here: https://github.com/VivSoftOrg/elasticsearch-kibana#enterprise-license
    keyJSON: ""
  # -- Values to passthrough to the elasticsearch-kibana chart: https://github.com/VivSoftOrg/elasticsearch-kibana.git
  values:
    kibana:
      image:
        repository: registry.gitlab.com/enbuild-staging/container_registry/elastic-kibana/kibana
    elasticsearch:
      image:
        repository: registry.gitlab.com/enbuild-staging/container_registry/elastic-elasticsearch/elasticsearch
    upgradeJob:
      image:
        repository: registry.gitlab.com/enbuild-staging/container_registry/big-bang-base
    bbtests:
      scripts:
        image: registry.gitlab.com/enbuild-staging/container_registry/stedolan-jq:1.6
  # -- Post Renderers.  See docs/postrenders.md
  postRenderers: []
