---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bigbang-secrets
  namespace: bigbang
spec:
  interval: 1440m0s
  sourceRef:
    kind: GitRepository
    name: bigbang-deploy
    namespace: bigbang
  path: "./bigbang/envs/dev/secrets/"
  prune: true
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bigbang-configmaps
  namespace: bigbang
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: bigbang-deploy
    namespace: bigbang
  path: "./bigbang/envs/dev/values/"
  prune: true
---