apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bigbang
spec:
  valuesFrom:
    - name: repo-values
      kind: Secret
    - name: istio-values
      kind: Secret
    - name: istiooperator-values
      kind: Secret
    - name: clusterAuditor-values
      kind: Secret
    - name: gatekeeper-values
      kind: Secret
    - name: twislock-values
      kind: Secret
    - name: eckoperator-values
      kind: Secret
    - name: fluentbit-values
      kind: Secret
    - name: monitoring-values
      kind: Secret
    - name: repo-values
      kind: ConfigMap
    - name: istio-values
      kind: ConfigMap
    - name: istiooperator-values
      kind: ConfigMap
    - name: clusterAuditor-values
      kind: ConfigMap
    - name: gatekeeper-values
      kind: ConfigMap
    - name: twislock-values
      kind: ConfigMap
    - name: eckoperator-values
      kind: ConfigMap
    - name: fluentbit-values
      kind: ConfigMap
    - name: monitoring-values
      kind: ConfigMap
