---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: secrets
  namespace: bigbang
spec:
  interval: 1m0s
  url: https://repo1.dso.mil/platform-one/private/abms-adce-partybus/partybus-bigbang-bootstrap.git
  ref:
    branch: develop
  secretRef:
    name: repository-credentials

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: bigbang
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: secrets
    namespace: bigbang
  path: "./apps/bigbang/envs/dev/secrets/"
  prune: true
  decryption:
    provider: sops
