{{- if .Values.gatekeeper.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: {{ .Release.Name }}-cluster-auditor
  name: cluster-auditor

---
{{- if and (ne .Values.registryCredentials.username "") (ne .Values.registryCredentials.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: private-registry
  namespace: cluster-auditor
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}