name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_bb:
    runs-on: ubuntu-latest
    # runs-on:  self-hosted
    if: ${{ contains(github.event.head_commit.message, 'run-ci') }}
    container:
      image: ghcr.io/vivsoftorg/hardened-github-runner:v2
      options: --user root
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" >> kubeconfig

      - name: Run deploy script
        run: |
          bash deploy.sh
        env:
          KUBECONFIG: './kubeconfig'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}