sso:
  # -- Toggle OIDC SSO for Kibana/Elasticsearch on and off.
  # Enabling this option will auto-create any required secrets.
  enabled: false

  # -- Elasticsearch/Kibana OIDC client ID
  client_id: ""

  # -- Elasticsearch/Kibana OIDC client secret
  client_secret: ""

license:
  # -- Toggle trial license installation of elasticsearch.  Note that enterprise (non trial) is required for SSO to work.
  trial: false

  # -- Elasticsearch license in json format
  keyJSON: ""

# -- Values to passthrough to the elasticsearch-kibana chart
values: {}
